create extension if not exists pgcrypto;

create table if not exists public.cars (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null,
  badge text,
  make text,
  model text,
  year text,
  price text not null,
  payment text,
  weekly_payment text,
  mileage text,
  body text,
  transmission text,
  fuel text,
  color text,
  drivetrain text,
  vin text,
  stock text,
  summary text,
  description text,
  image text,
  status text not null default 'available' check (status in ('available', 'hidden', 'sold')),
  featured boolean not null default false,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.car_images (
  id bigint generated by default as identity primary key,
  car_id bigint not null references public.cars(id) on delete cascade,
  image_url text not null,
  sort_order integer not null default 0,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text,
  email text,
  car_interest text,
  car_id bigint references public.cars(id) on delete set null,
  source text not null default 'site',
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.appointments (
  id bigint generated by default as identity primary key,
  lead_id bigint not null references public.leads(id) on delete cascade,
  car_id bigint references public.cars(id) on delete set null,
  preferred_date date,
  source text not null default 'site',
  status text not null default 'pending' check (status in ('pending', 'confirmed', 'done', 'cancelled')),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.subscribers (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  source text not null default 'site',
  created_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists subscribers_email_unique_idx on public.subscribers (lower(email));
create unique index if not exists cars_vin_unique_idx on public.cars (vin) where vin is not null and btrim(vin) <> '';
create index if not exists car_images_car_id_idx on public.car_images (car_id, sort_order);
create index if not exists leads_car_id_idx on public.leads (car_id);
create index if not exists appointments_lead_id_idx on public.appointments (lead_id);
create index if not exists appointments_car_id_idx on public.appointments (car_id);
create index if not exists appointments_status_idx on public.appointments (status);

alter table public.cars enable row level security;
alter table public.car_images enable row level security;
alter table public.leads enable row level security;
alter table public.appointments enable row level security;
alter table public.subscribers enable row level security;

drop policy if exists "Public can read cars" on public.cars;
create policy "Public can read cars"
on public.cars
for select
to anon, authenticated
using (true);

drop policy if exists "Public can read car images" on public.car_images;
create policy "Public can read car images"
on public.car_images
for select
to anon, authenticated
using (true);
